backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "activities"
    label: "الأنشطة"
    folder: "content/activities"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "التاريخ", name: "date", widget: "datetime"}
      - {label: "الصورة الرئيسية", name: "thumbnail", widget: "image"}
      - {label: "ألبوم الصور (الأرشيف)", name: "gallery", widget: "list", field: {label: "صورة", name: "image", widget: "image"}, required: false}
      - {label: "التفاصيل", name: "body", widget: "markdown"}
